
const preBuildCards = [
    {
        cardName:'Pikachu',
        cardDescription:'O pokemon que após horas, encontra o erro no código  e incrédulo constata que era um tipo declarado errado',
        cardImage:'https://c.tenor.com/UZJd1pjj4NMAAAAM/surprised-pikachu.gif',
        cardRare:'normal',
        cardAttr1:'25',
        cardAttr2:'15',
        cardAttr3:'5',
        cardTrunfo:false,
    },
    {
        cardName:'Torchic',
        cardDescription:'Sempre alegre por terminar os projetos no prazo e com todos os requisitos obrigatórios',
        cardImage:'https://c.tenor.com/odzUn59ZNhUAAAAC/pokemon-funny.gif',
        cardRare:'muito raro',
        cardAttr1:'80',
        cardAttr2:'90',
        cardAttr3:'65',
        cardTrunfo:false,
    },
    {
        cardName:'Squirtle',
        cardDescription:'Super confiante em suas capacidades programadoras, não entende o porquê de tantas linhas de erro no console',
        cardImage:'https://i.pinimg.com/originals/67/01/fd/6701fd96258bffa0085a98a8673719f3.gif',
        cardRare:'raro',
        cardAttr1:'95',
        cardAttr2:'30',
        cardAttr3:'70',
        cardTrunfo:false,
    },
    {
        cardName:'Psyduck',
        cardDescription:'Sempre em dúvida de por qual requisito começar, muitas vezes se arrisca a iniciar o projeto pelo CSS',
        cardImage:'https://gifdb.com/images/thumbnail/confused-pokemon-psyduck-6zrcjs7uny2qeu66.gif',
        cardRare:'raro',
        cardAttr1:'30',
        cardAttr2:'10',
        cardAttr3:'10',
        cardTrunfo:false,
    },
    {
        cardName:'Totodile',
        cardDescription:'Aquele que não se amedronta com o tamanho do projeto e sempre cai de cabeça',
        cardImage:'https://i.pinimg.com/originals/e9/ff/d4/e9ffd442023a27ab89377af62694d5c0.gif',
        cardRare:'muito raro',
        cardAttr1:'99',
        cardAttr2:'10',
        cardAttr3:'80',
        cardTrunfo:false,
    },
    {
        cardName:'Charmander',
        cardDescription:'Sempre orgulhoso de começar um novo projeto, mesmo sem ter terminados os antigos',
        cardImage:'https://i.pinimg.com/originals/b5/13/28/b51328854f9214688f594d76b7a45a49.gif',
        cardRare:'normal',
        cardAttr1:'60',
        cardAttr2:'45',
        cardAttr3:'20',
        cardTrunfo:false,
    },
]

export default preBuildCards;